import type { CategoryId } from './categories';

/**
 * The single list of public projects. The homepage, the Projects page, case-study headers
 * and footers, the sitemap, the command palette and page metadata all read from here.
 *
 * Card rules (AGENTS.md): `summary` is one sentence of roughly ten words, `tags` holds two.
 * Card images are web-sized crops built by `scripts/build-card-images.py`.
 */

export const projectSlugs = [
  'mumosa-crisis-response-vr',
  'birdwatching',
  'shift-culture-vr',
  'vr-drift-simulator',
  'patapon-vr-the-first-beat',
  'shinobi-story',
  'shinobi-story-2',
  'lizard-wizard',
  'shonen-showdown',
  'prince-of-persia-warrior-within-mod',
  'guilty-as-arrr',
  'shogun-flowers-fall-in-blood',
  'bg3-toolkit-modding',
  'fallout-level-design',
  'totally-bugged-out',
  'cranky-game-jam',
  'cranky-squirrel-annihilator',
  'trash-been',
  'the-signal',
  'the-last-paycheck',
  'black-dice-engine',
  'ami-research-companion',
  'feh-barracks-manager',
  'tur-workout-tracker',
  'comfyui-production-pipeline',
  'horror-vn-kit',
  'legion-go-console-dock',
  'figuresmith',
  'cpse',
] as const;

export type ProjectSlug = (typeof projectSlugs)[number];

export type ProjectStatus =
  | 'Released'
  | 'Delivered'
  | 'Completed'
  | 'Playable'
  | 'Prototype'
  | 'In development'
  | 'Concept';

export interface Project {
  slug: ProjectSlug;
  href: string;
  title: string;
  /** One sentence, roughly ten words. */
  summary: string;
  /** Two at most: usually the engine or medium, then the angle. */
  tags: readonly [string, string];
  categories: readonly CategoryId[];
  /** Drives "Next in …" and the case-study kicker. */
  primaryCategory: CategoryId;
  status: ProjectStatus;
  /** What Georgi did, in one line. */
  role: string;
  card: { src: string; alt: string; position?: string };
  searchTerms?: readonly string[];
}

const card = (slug: string, alt: string, position?: string) => ({
  src: `/images/cards/${slug}.jpg`,
  alt,
  position,
});

export const projects: Record<ProjectSlug, Project> = {
  'mumosa-crisis-response-vr': {
    slug: 'mumosa-crisis-response-vr',
    href: '/projects/mumosa-crisis-response-vr',
    title: 'MUMOSA Crisis Response',
    summary: 'Spatial evidence review for an Army Research Laboratory dashboard.',
    tags: ['Unreal Engine', 'Client research'],
    categories: ['xr', 'tools'],
    primaryCategory: 'xr',
    status: 'Delivered',
    role: 'Led research and spatial prototyping; contributed to the dashboard information architecture',
    card: card('mumosa-crisis-response-vr', 'Evidence marker selected inside the MUMOSA Unreal crisis-response scene'),
    searchTerms: ['mumosa', 'army research laboratory', 'arl', 'crisis response', 'situational awareness', 'dashboard', 'unreal', 'evidence review', 'vr'],
  },
  birdwatching: {
    slug: 'birdwatching',
    href: '/projects/birdwatching',
    title: 'Birdwatching VR',
    summary: 'Photograph birds in VR and fill a star-rated field guide.',
    tags: ['Unity 6', 'PCVR / Quest'],
    categories: ['xr'],
    primaryCategory: 'xr',
    status: 'Prototype',
    role: 'Camera capture, bird scoring, field-guide progress, backpack tools, comfort settings and builds',
    card: card('birdwatching', 'Stylised forest environment from Birdwatching VR'),
    searchTerms: ['birdwatching', 'vr', 'unity', 'xr', 'bird photography', 'bingo book', 'camera', 'quest', 'openxr', 'comfort'],
  },
  'shift-culture-vr': {
    slug: 'shift-culture-vr',
    href: '/projects/shift-culture-vr',
    title: 'Shift Culture VR',
    summary: 'Dirt-bike safety simulation for first-time VR users.',
    tags: ['Unity', 'Mobile VR'],
    categories: ['xr'],
    primaryCategory: 'xr',
    status: 'Prototype',
    role: 'Technical implementation, VR interaction flow, gameplay feel and comfort testing',
    card: card('shift-culture-vr', 'B-360 dirt-bike safety simulator on a tree-lined road'),
    searchTerms: ['shift culture', 'b-360', 'b360', 'dirt bike', 'safety training', 'mobile vr', 'riding'],
  },
  'vr-drift-simulator': {
    slug: 'vr-drift-simulator',
    href: '/projects/vr-drift-simulator',
    title: 'VR Car Drift Simulator',
    summary: 'VR drift simulator with tuned vehicle physics and cockpit feedback.',
    tags: ['Unity', 'Vehicle physics'],
    categories: ['xr'],
    primaryCategory: 'xr',
    status: 'Prototype',
    role: 'Vehicle handling, XR interaction, cockpit feedback, technical structure and UX evaluation',
    card: card('vr-drift-simulator', 'Chase-camera drift shot on a lit city expressway'),
    searchTerms: ['drift', 'car', 'driving', 'vehicle dynamics', 'simulator', 'drift immersive'],
  },
  'patapon-vr-the-first-beat': {
    slug: 'patapon-vr-the-first-beat',
    href: '/projects/patapon-vr-the-first-beat',
    title: 'Patapon VR: The First Beat',
    summary: 'A VR rhythm-strategy design concept built on Patapon.',
    tags: ['VR concept', 'Rhythm strategy'],
    categories: ['xr', 'gameplay'],
    primaryCategory: 'xr',
    status: 'Concept',
    role: 'Solo systems, interaction and narrative designer',
    card: card('patapon-vr-the-first-beat', 'Patapon boss battle artwork used as concept reference'),
    searchTerms: ['patapon', 'rhythm', 'strategy', 'gdd', 'concept'],
  },
  'shinobi-story': {
    slug: 'shinobi-story',
    href: '/projects/shinobi-story',
    title: 'Shinobi Story',
    summary: 'Custom Naruto MMORPG with 1M+ downloads and $110K revenue.',
    tags: ['Live game', 'MMORPG'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Released',
    role: 'Live operations, content planning, animation, player support, marketing and developer mentoring',
    card: card('shinobi-story', 'Shinobi Story character charging through a forest'),
    searchTerms: ['shinobi', 'naruto', 'mmorpg', 'byond', 'live ops', 'community', 'pixel bulb'],
  },
  'shinobi-story-2': {
    slug: 'shinobi-story-2',
    href: '/projects/shinobi-story-2',
    title: 'Shinobi Story 2',
    summary: 'The Unreal Engine 5 sequel: my character creator UI and traversal.',
    tags: ['Unreal Engine 5', 'UI design'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'In development',
    role: 'Co-owner. Sole UI designer and implementer; traversal programmer alongside the team',
    card: card('shinobi-story-2', 'Shinobi Story 2 character creator with hanging talisman menus'),
    searchTerms: ['shinobi story 2', 'ss2', 'unreal', 'ue5', 'character creator', 'ui', 'traversal', 'wall run', 'c++'],
  },
  'lizard-wizard': {
    slug: 'lizard-wizard',
    href: '/projects/lizard-wizard',
    title: 'Lizard Wizard',
    summary: 'Five-person Unity capstone: production setup and predator sensing AI.',
    tags: ['Unity 6', 'Enemy AI'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'In development',
    role: 'Production setup lead and predator AI programmer on a five-person team',
    card: card('lizard-wizard', 'Spider vision cone and hearing radius gizmos in a desert sandbox'),
    searchTerms: ['lizard wizard', 'capstone', 'spider', 'predator', 'sensing', 'state machine', 'platformer'],
  },
  'shonen-showdown': {
    slug: 'shonen-showdown',
    href: '/projects/shonen-showdown',
    title: 'Shonen Showdown',
    summary: 'Networked first-person card game on a reusable rules engine.',
    tags: ['Unity 6', 'Photon Fusion 2'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Prototype',
    role: 'Lead developer for battle rules, turn flow, networking and card-data architecture',
    card: card('shonen-showdown', 'First-person duel view from Shonen Showdown'),
    searchTerms: ['shonen', 'card game', 'tcg', 'anime', 'rules engine', 'networking', 'photon'],
  },
  'prince-of-persia-warrior-within-mod': {
    slug: 'prince-of-persia-warrior-within-mod',
    href: '/projects/prince-of-persia-warrior-within-mod',
    title: 'Prince of Persia: Warrior Within Mod',
    summary: 'Slay the Spire 2 character mod with rewinds and a Sand economy.',
    tags: ['Godot / C#', 'Game modding'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Playable',
    role: 'Solo designer and gameplay engineer; also integration, assets, audio and presentation',
    card: card('prince-of-persia-warrior-within-mod', 'Prince of Persia mod character select screen in Slay the Spire 2'),
    searchTerms: ['prince of persia', 'warrior within', 'slay the spire 2', 'mod', 'godot', 'harmony', 'dahaka', 'rewind'],
  },
  'guilty-as-arrr': {
    slug: 'guilty-as-arrr',
    href: '/projects/guilty-as-arrr',
    title: 'Guilty As Arrr',
    summary: 'Networked pirate social-deduction game with proximity voice chat.',
    tags: ['Photon Fusion', 'Multiplayer'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Prototype',
    role: 'Team lead, systems developer and playtest coordinator',
    card: card('guilty-as-arrr', 'Guilty As Arrr playtest on a pirate ship deck'),
    searchTerms: ['guilty as arrr', 'pirate', 'social deduction', 'photon voice', 'spatial audio', 'repo-x'],
  },
  'shogun-flowers-fall-in-blood': {
    slug: 'shogun-flowers-fall-in-blood',
    href: '/projects/shogun-flowers-fall-in-blood',
    title: 'Shogun: Flowers Fall in Blood',
    summary: 'Mobile tactical RPG prototype with grid combat and progression.',
    tags: ['Unity', 'Tactical RPG'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'In development',
    role: 'Solo designer and developer',
    card: card('shogun-flowers-fall-in-blood', 'Samurai character art from Shogun: Flowers Fall in Blood'),
    searchTerms: ['shogun', 'tactical rpg', 'gacha', 'mobile', 'grid combat'],
  },
  'bg3-toolkit-modding': {
    slug: 'bg3-toolkit-modding',
    href: '/projects/bg3-toolkit-modding',
    title: "Baldur's Gate 3 Modding",
    summary: 'Toolkit scripting for dialogue, flags, skill checks and Osiris.',
    tags: ['BG3 Toolkit', 'Gameplay scripting'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'In development',
    role: 'Solo modder, learning the Toolkit from scratch',
    card: card('bg3-toolkit-modding', "Baldur's Gate 3 Modding title card"),
    searchTerms: ["baldur's gate 3", 'bg3', 'toolkit', 'osiris', 'dialogue', 'skill check', 'larian', 'mod'],
  },
  'fallout-level-design': {
    slug: 'fallout-level-design',
    href: '/projects/fallout-level-design',
    title: 'Fallout 4 Level Design',
    summary: 'One floor of a team-built Fallout 4 interior, merged and polished.',
    tags: ['Level design', 'Team mod'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Completed',
    role: 'Third-floor level designer and merge support',
    card: card('fallout-level-design', 'Hall of Idols puzzle chamber in the Fallout 4 level'),
    searchTerms: ['fallout', 'fallout 4', 'modding', 'level design', 'creation kit', 'hall of idols'],
  },
  'totally-bugged-out': {
    slug: 'totally-bugged-out',
    href: '/projects/totally-bugged-out',
    title: 'Totally Bugged Out',
    summary: 'First-person bug survival prototype with swarming enemy AI.',
    tags: ['Unity', 'Enemy AI'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Playable',
    role: 'Solo designer and developer',
    card: card('totally-bugged-out', 'Totally Bugged Out key art'),
    searchTerms: ['bugs', 'survival', 'first-person', 'swarm ai'],
  },
  'cranky-game-jam': {
    slug: 'cranky-game-jam',
    href: '/projects/cranky-game-jam',
    title: 'Cranky (Game Jam 2024)',
    summary: 'Split-screen pug chaos built in one week for Global Game Jam.',
    tags: ['Unity', 'Game jam'],
    categories: ['gameplay', 'creative'],
    primaryCategory: 'gameplay',
    status: 'Completed',
    role: 'Project manager, 3D artist and animator',
    card: card('cranky-game-jam', 'Cranky pug character rig and animation controls in Blender'),
    searchTerms: ['cranky', 'pug', 'squirrels', 'global game jam', 'local multiplayer', 'animation'],
  },
  'cranky-squirrel-annihilator': {
    slug: 'cranky-squirrel-annihilator',
    href: '/projects/cranky-squirrel-annihilator',
    title: 'Cranky: The Squirrel Annihilator',
    summary: 'Solo first-person pug game with reactive AI and a WebGL build.',
    tags: ['Unity', 'Solo build'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Playable',
    role: 'Solo developer, designer and 3D artist',
    card: card('cranky-squirrel-annihilator', 'Cranky: The Squirrel Annihilator banner'),
    searchTerms: ['cranky', 'squirrel annihilator', 'pug', 'webgl', 'enemy ai'],
  },
  'trash-been': {
    slug: 'trash-been',
    href: '/projects/trash-been',
    title: 'Trash Been',
    summary: 'One-week solo platformer about cleaning up a polluted city.',
    tags: ['Unity', 'Solo build'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Completed',
    role: 'Solo designer and developer',
    card: card('trash-been', 'Trash Been title art'),
    searchTerms: ['trash been', 'breda', 'platformer', 'pollution', 'webgl', 'visual scripting'],
  },
  'the-signal': {
    slug: 'the-signal',
    href: '/projects/the-signal',
    title: 'The Signal',
    summary: 'Sci-fi co-op board game with modular exploration and evolving enemies.',
    tags: ['Board game', 'Systems design'],
    categories: ['gameplay'],
    primaryCategory: 'gameplay',
    status: 'Completed',
    role: 'Systems and narrative designer on a three-person team',
    card: card('the-signal', 'The Signal board game banner'),
    searchTerms: ['the signal', 'board game', 'sci-fi', 'co-op', 'tabletop'],
  },
  'the-last-paycheck': {
    slug: 'the-last-paycheck',
    href: '/projects/the-last-paycheck',
    title: 'The Last Paycheck',
    summary: 'Design document for a 2050 survival game about poverty and work.',
    tags: ['Narrative design', 'Design document'],
    categories: ['gameplay', 'creative'],
    primaryCategory: 'gameplay',
    status: 'Concept',
    role: 'Solo narrative and systems designer',
    card: card('the-last-paycheck', 'The Last Paycheck banner'),
    searchTerms: ['last paycheck', 'dystopian', '2050', 'poverty', 'narrative', 'gdd'],
  },
  'black-dice-engine': {
    slug: 'black-dice-engine',
    href: '/projects/black-dice-engine',
    title: 'Black Dice Engine',
    summary: 'A local game-master engine for tabletop RPG campaigns.',
    tags: ['TypeScript', 'Local AI'],
    categories: ['tools', 'gameplay'],
    primaryCategory: 'tools',
    status: 'Prototype',
    role: 'Solo product architect and gameplay-systems engineer',
    card: card('black-dice-engine', 'Black Dice Engine dice artwork'),
    searchTerms: ['black dice', 'game master', 'ttrpg', 'tabletop', 'rpg', 'local first', 'rules engine'],
  },
  'ami-research-companion': {
    slug: 'ami-research-companion',
    href: '/projects/ami-research-companion',
    title: 'Ami',
    summary: 'A local research companion that answers with its sources.',
    tags: ['Python', 'Local-first AI'],
    categories: ['tools'],
    primaryCategory: 'tools',
    status: 'Delivered',
    role: 'Solo product designer and developer',
    card: card('ami-research-companion', 'Ami answering a question with illustrated evidence'),
    searchTerms: ['ami', 'research companion', 'medical research', 'mac app', 'local-first', 'retrieval'],
  },
  'feh-barracks-manager': {
    slug: 'feh-barracks-manager',
    href: '/projects/feh-barracks-manager',
    title: 'FEH Barracks Manager',
    summary: 'Fire Emblem Heroes companion app with synced collections.',
    tags: ['Next.js', 'Data pipeline'],
    categories: ['tools'],
    primaryCategory: 'tools',
    status: 'In development',
    role: 'Solo developer: product design, frontend, data ingestion, releases and launcher',
    card: card('feh-barracks-manager', 'FEH Barracks Manager searchable hero library'),
    searchTerms: ['feh', 'fire emblem heroes', 'barracks', 'supabase', 'electron', 'scraper', 'launcher'],
  },
  'tur-workout-tracker': {
    slug: 'tur-workout-tracker',
    href: '/projects/tur-workout-tracker',
    title: 'TUR Workout Tracker',
    summary: 'Offline-first iPhone workout log with a Garmin watch companion.',
    tags: ['SwiftUI', 'Garmin Connect IQ'],
    categories: ['tools'],
    primaryCategory: 'tools',
    status: 'In development',
    role: 'Solo developer and designer: product, iOS app, watch app, data, brand and website',
    card: card('tur-workout-tracker', 'TUR app Today screen with the next workout'),
    searchTerms: ['tur', 'gym', 'workout', 'fitness', 'iphone', 'ios', 'swift', 'garmin', 'watch', 'hyrox'],
  },
  'comfyui-production-pipeline': {
    slug: 'comfyui-production-pipeline',
    href: '/projects/comfyui-production-pipeline',
    title: 'ComfyUI Production Pipeline',
    summary: 'Local AI image pipeline for lookdev and asset cleanup.',
    tags: ['ComfyUI', 'Asset pipeline'],
    categories: ['tools', 'creative'],
    primaryCategory: 'tools',
    status: 'Prototype',
    role: 'Workflow designer, prompt author and asset-cleanup owner',
    card: card('comfyui-production-pipeline', 'Prince of Persia character sheet after background removal in the ComfyUI cleanup workflow'),
    searchTerms: ['comfyui', 'ai art', 'workflow', 'image generation', 'asset cleanup', 'lookdev'],
  },
  'horror-vn-kit': {
    slug: 'horror-vn-kit',
    href: '/projects/horror-vn-kit',
    title: 'Horror VN Kit',
    summary: 'No-code Unity toolkit for branching horror visual novels.',
    tags: ['Unity', 'Tools programming'],
    categories: ['tools', 'creative'],
    primaryCategory: 'tools',
    status: 'Delivered',
    role: 'Toolkit programmer and tools designer',
    card: card('horror-vn-kit', 'Horror VN Kit scene with a character and two branching choices'),
    searchTerms: ['horror', 'visual novel', 'vn', 'dialogue', 'branching', 'editor tool', 'eden'],
  },
  'legion-go-console-dock': {
    slug: 'legion-go-console-dock',
    href: '/projects/legion-go-console-dock',
    title: 'Legion Go Console Dock',
    summary: '3D-printable handheld dock with active cooling and NFC game cards.',
    tags: ['Blender CAD', '3D printing'],
    categories: ['tools'],
    primaryCategory: 'tools',
    status: 'Prototype',
    role: 'Solo hardware design: requirements, Blender CAD, print preparation and wiring plan',
    card: card('legion-go-console-dock', 'Exploded render of the Legion Go dock lid and chassis'),
    searchTerms: ['legion go', 'dock', 'handheld', 'blender', '3d print', 'nfc', 'cooling', 'hardware'],
  },
  figuresmith: {
    slug: 'figuresmith',
    href: '/projects/figuresmith',
    title: 'Figuresmith',
    summary: 'My figurine studio: printing, hand painting and custom LEDs.',
    tags: ['3D printing', 'Small business'],
    categories: ['creative'],
    primaryCategory: 'creative',
    status: 'Completed',
    role: 'Founder, owner and independent maker',
    card: card('figuresmith', 'Painted figurine from a Figuresmith process video'),
    searchTerms: ['figuresmith', 'v4n', 'figurine', 'statue', 'resin', 'painting', 'leds', 'llc'],
  },
  cpse: {
    slug: 'cpse',
    href: '/cpse',
    title: 'UMD CPSE Media Work',
    summary: 'Program and recruitment videos for a UMD engineering program.',
    tags: ['Videography', 'Editing'],
    categories: ['creative'],
    primaryCategory: 'creative',
    status: 'Delivered',
    role: 'Digital & visual media specialist; social media and marketing content creator',
    card: card('cpse', 'UMD CPSE Summer Program 2024 video still'),
    searchTerms: ['cpse', 'umd', 'university of maryland', 'video', 'social media', 'recruitment'],
  },
};

/** Order of the full list and of each category view (most relevant first). */
export const allOrder: readonly ProjectSlug[] = [
  'mumosa-crisis-response-vr',
  'shinobi-story',
  'shinobi-story-2',
  'black-dice-engine',
  'birdwatching',
  'shonen-showdown',
  'ami-research-companion',
  'tur-workout-tracker',
  'prince-of-persia-warrior-within-mod',
  'shift-culture-vr',
  'lizard-wizard',
  'feh-barracks-manager',
  'comfyui-production-pipeline',
  'vr-drift-simulator',
  'guilty-as-arrr',
  'horror-vn-kit',
  'shogun-flowers-fall-in-blood',
  'bg3-toolkit-modding',
  'fallout-level-design',
  'legion-go-console-dock',
  'cpse',
  'figuresmith',
  'totally-bugged-out',
  'cranky-squirrel-annihilator',
  'cranky-game-jam',
  'trash-been',
  'the-signal',
  'patapon-vr-the-first-beat',
  'the-last-paycheck',
];
